### ISSUE TITLE
Help with installation and tutorial

### ISSUE THREAD

**Issue by s-peu5** [poldracklab/nitransforms#115]
Hi
I'm trying to use nitransforms to convert an ANTs affine transform to an AFNI-compatible one.
I couldn't find much documentation on nitransforms, except for the paper "SOFTWARE TOOL TO READ, REPRESENT, MANIPULATE, AND APPLY N-DIMENSIONAL SPATIAL TRANSFORMS".
After installation, I couldn't fin the function io.load that appears on the paper.
Is there any more detailed guide to this program?
Thank you

**Comment by oesteban** [comment]
Hi @s-peu5, at the moment the documentation is still scarce. There's this executable demo - https://mybinder.org/v2/gh/poldracklab/nitransforms/master?filepath=docs%2Fnotebooks%2F (with the caveat that it is pretty resource-demanding and oftentimes it fails).

Inside that demo there are jupyter books you can run: https://github.com/poldracklab/nitransforms/tree/master/docs/notebooks

Installation should be as easy as:

```Bash
pip install nitransforms
```

After that, on a python prompt you should be able to check the installation:

```Python
>>> from nitransforms import __version__
>>> print(__version__)
```

**Comment by oesteban** [comment]
Hi @s-peu5, I hope you finally managed to get the conversion done - if not, please open up a new issue.

Regarding documentation, we have expanded the base documents and made it more accessible through readthedocs - https://nitransforms.readthedocs.io/en/latest/
