### ISSUE TITLE
`DeprecationWarning` with scipy 1.8.0

### ISSUE THREAD

**Issue by HippocampusGirl** [poldracklab/nitransforms#149]
When using nitransforms version 20.0.0rc5, I get the following warnings with scipy 1.8.0

```
/usr/local/miniconda/lib/python3.10/site-packages/nitransforms/io/base.py:4: DeprecationWarning: Please use `get_matfile_version` from the `scipy.io.matlab` namespace, the `scipy.io.matlab.miobase` namespace is deprecated.
/usr/local/miniconda/lib/python3.10/site-packages/nitransforms/io/base.py:5: DeprecationWarning: Please use `MatFile4Reader` from the `scipy.io.matlab` namespace, the `scipy.io.matlab.mio4` namespace is deprecated.
/usr/local/miniconda/lib/python3.10/site-packages/nitransforms/io/base.py:6: DeprecationWarning: Please use `MatFile5Reader` from the `scipy.io.matlab` namespace, the `scipy.io.matlab.mio5` namespace is deprecated.
```

These point to the code here:

https://github.com/poldracklab/nitransforms/blob/d81d93ae07b980c2266880769da2b5a919d7b5a4/nitransforms/io/base.py#L5-L7

I would greatly appreciate if you could fix these :-) Thank you so much

**Comment by oesteban** [comment]
I'll try to get to this ASAP, but if you get ahead and submit a PR -- that will be very much appreciated (and speedy).

**Comment by HippocampusGirl** [comment]
I just had a look, and my first question would be what is the purpose of the `_read_mat` method? 

As far as I can tell, it's basically a re-implementation of `scipy`'s `loadmat` (compare https://github.com/scipy/scipy/blob/b5d8bab88af61d61de09641243848df63380a67f/scipy/io/matlab/_mio.py#L73-L82). 

Was there at some point a problem with `scipy`'s `loadmat`?

**Comment by HippocampusGirl** [comment]
Oh that makes sense, maybe they only introduced that later. In that case, I will remove `_read_mat` and send a pull request :-)
