### ISSUE TITLE
FLIRT 6.0 (FSL 6.0.2) linear tests fail

### ISSUE THREAD

**Issue by smoia** [poldracklab/nitransforms#52]
In `test_linear.py`, `test_apply_linear_transform` fails for all the parametrisations `sw_tool='fsl'`, with a fresh install of FSL 6.0.2 (FLIRT 6.0).
It's an assertion error due to the difference being higher than the tolerance.
This doesn't happen in the travis CI tests, so I assume it is due to the different version of FSL.

**Comment by oesteban** [comment]
This could be related, although we are using 3D images - Washington-University/HCPpipelines#118

I'm investigating this right now (cc @effigies, for any quick insights I might want to check).

**Comment by oesteban** [comment]
Okay, I'm chatting with Matthew Webster and Fidel Alfaro-Almagro about this issue and will report back ASAP. It seems there is a bug in FSL 6 resampling. If feels like the option `-setbackground 0` has stopped being honored or maybe has changed its behavior. The outcome artifact is that there's a rotation frame around the resampled images that is filled with zeros for nitransforms and FSL 5, but it's a constant nonzero number for FSL 6.

For the moment, and to make all these tests less brittle, I'm going to look for intensity differences only within the brain mask.

**Comment by satra** [comment]
there is another issue we came across recently using the applyisoxfm in flirt, which gave us weird issues that we could only uncover in the tsnr maps. they affected the std dev maps and looked like a checkerboard pattern.  i replaced the script with a nitransforms version that did not have the effect. i was going to write this up and send to the FSL folks, but haven't had the time. this wasn't a direct case of before and after, but it's possible that something fundamental changed in the resampling behavior in flirt.

**Comment by oesteban** [comment]
The plot thickens - when I looked at the differences within the brain mask, there are still differences between FSL 5 and 6. These were masked by the out-of-bounds constant value I first checked.
