### ISSUE TITLE
Packaging issue: modules not visible

### ISSUE THREAD

**Issue by oesteban** [poldracklab/nitransforms#91]
It seems modules (i.e., python files) are not automatically visible in their package (e.g., `nitransforms.io`, unless explicit imports are set in the `__init__.py` of the package.

In other words, this code:
```Python
from nitransforms.manip import TransformChain
```

doesn't work, unless we add the line
```Python
from . import manip
```
to `nitransforms/__init__.py`.

I might be misinterpreting how the default packaging works, but I believe we have some bad setting in the `setup.cfg` instead.

I know @effigies has dealt quite a bit with setuptools, pep517, etc. - any quick ideas of why this is happening? or this is actually not a bug?

**Comment by effigies** [comment]
You've put an `__all__` in `__init__.py`. That seems likely to make things hard to access.

**Comment by oesteban** [comment]
Okay, in fact not a bug. Thanks for the clarification.
